# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rendered',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
