# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_rendered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content_rendered',
            field=models.TextField(editable=False),
        ),
    ]
