# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('institute', models.CharField(max_length=40)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('twitter', models.SlugField(max_length=40)),
                ('facebook', models.SlugField(max_length=40)),
                ('github', models.SlugField(max_length=40)),
                ('linkedin', models.SlugField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=80)),
                ('summary', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='skills_familiar',
            field=models.ManyToManyField(related_name='skills_familiar', to='cvdb.Skill'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills_proficiency',
            field=models.ManyToManyField(related_name='skills_proficiency', to='cvdb.Skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdb.Person'),
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdb.Person'),
        ),
    ]
