# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdb', '0002_auto_20180325_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_familiar',
            field=models.ManyToManyField(related_name='skills_familiar', to='cvdb.Skill'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_proficiency',
            field=models.ManyToManyField(related_name='skills_proficiency', to='cvdb.Skill'),
        ),
    ]
